### PR TITLE
Added 404 Page

### PR DESCRIPTION
**Pull request by doublevcodes**
I have created a simple `error.html` Page which is the 404 page. It has a matching stylesheet- `error.css`. Please forgive my terrible css... I’m sleepy.

### CODE REVIEW

**Comment by nopeless** [comment]
did you test this with the full server running on your computer?

**Comment by nopeless** [comment]
@rickastley1

**Comment by doublevcodes** [comment]
I did it on my phone on [repl.it](https://repl.it)
And anyway, I'm still working on it. Just leave the PR open for a bit whilst I make the page better.

**Comment by doublevcodes** [comment]
I finished it so you can merge if you think it's ok

**Comment by nopeless** [comment]
you know you can just rewrite history

**Comment by doublevcodes** [comment]
What

**Comment by doublevcodes** [comment]
Rem told me that rewriting history isn't good

**Comment by nopeless** [comment]
@rickastley1 i made changes to main. now you can test it using express instead of using code pen or something else. i included details on how to test the thing on readme. pull main, change the error catching line on app.js, then comment here to notify me

**Comment by nopeless** [comment]
ill fix this mysefl

**Review by amadejsky — COMMENTED** [review]
lgfm!

**Comment by nopeless** [comment]
sry this is ded project and would probably go through a rewrite but thanks for review 👍👍

**Pull request closed without merging**
